version: "3"
services:
  ssr:
    build:
      context: .
      dockerfile: ./Dockerfile-ssr
      args:
        - SSR_PORT=4443
        - SSR_PASSWD=REALY_SAFE_PASSWORD
        - SSR_METHOD=chacha20
        - SSR_PROTOCOL=auth_aes128_md5
        - SSR_OBFS=tls1.2_ticket_fastauth
    volumes:
      - ./shadowsocks-r:/etc/init.d/shadowsocks-r
    restart: always
    network_mode: bridge
    #ports:
    #  - "4443"
  nginx:
    links:
      - ssr
    depends_on:
      - ssr
    image: ykfq/nginx-with-stream:1.12.2
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/conf.d:/etc/nginx/conf.d
      - ./conf/conf.d.stream:/etc/nginx/conf.d.stream
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
      - "4443:4443"
    network_mode: bridge
