FROM ubuntu:18.04

ARG SSR_PORT
ARG SSR_PASSWD
ARG SSR_METHOD
ARG SSR_PROTOCOL
ARG SSR_OBFS

ENV SSR_PORT=${SSR_PORT}
ENV SSR_PASSWD=${SSR_PASSWD}
ENV SSR_METHOD=${SSR_METHOD}
ENV SSR_PROTOCOL=${SSR_PROTOCOL}
ENV SSR_OBFS=${SSR_OBFS}

WORKDIR /root

RUN ["bash", "-c", " \
    apt-get update && \
    apt-get -y install vim net-tools telnet iproute2 curl && \
    curl -o ssr.sh https://raw.githubusercontent.com/ykfq/nginx-with-stream/master/ssr.sh && \
    bash ssr.sh install ${SSR_PORT} ${SSR_PASSWD} ${SSR_METHOD} ${SSR_PROTOCOL} ${SSR_OBFS}" ] > ssr.log 2&>1

CMD [ "bash", "-c", "/etc/init.d/shadowsocks-r restart && tail -f ssr.log" ]
