version: "3"
services:
  ssr:
    build:
      context: .
      dockerfile: ./Dockerfile-ssr
      args:
        - SSR_PORT=443
        - SSR_PASSWD=timanetworks.com
        - SSR_METHOD=chacha20
        - SSR_PROTOCOL=auth_aes128_md5
        - SSR_OBFS=tls1.2_ticket_fastauth
    restart: always
    #ports:
    #  - "443"
  nginx:
    links:
      - ssr
    depends_on:
      - ssr
    image: ykfq/nginx-with-stream:1.12.2
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/conf.d:/etc/nginx/conf.d
      - ./conf/conf.d.stream:/etc/nginx/conf.d.stream
    ports:
      - "80:80"
      - "443:443"